theme = "nord-dark"
icons = "awesome"

#[[block]]
#block = "focused_window"
#max_width = 30
#show_marks = "visible"

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"


[[block]]
block = "disk_space"
path = "/"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
info_type = "available"
format = "{icon} {used}/{total} ({available} free)"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

#[[block]]
#block = "load"
#interval = 1
#format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "backlight"

[[block]]
block = "time"
interval = 5
format = "%a %d %b %I:%M %p"

[[block]]
block = "net"
format = "{ssid} {signal_strength} {speed_down;K*b}"
interval = 5

